//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI1_2_3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IService1/CelsiusToFahrenheitResponse")]
        int CelsiusToFahrenheit(int celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CelsiusToFahrenheit", ReplyAction="http://tempuri.org/IService1/CelsiusToFahrenheitResponse")]
        System.Threading.Tasks.Task<int> CelsiusToFahrenheitAsync(int celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IService1/FahrenheitToCelsiusResponse")]
        int FahrenheitToCelsius(int fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FahrenheitToCelsius", ReplyAction="http://tempuri.org/IService1/FahrenheitToCelsiusResponse")]
        System.Threading.Tasks.Task<int> FahrenheitToCelsiusAsync(int fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortNumbers", ReplyAction="http://tempuri.org/IService1/SortNumbersResponse")]
        string SortNumbers(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortNumbers", ReplyAction="http://tempuri.org/IService1/SortNumbersResponse")]
        System.Threading.Tasks.Task<string> SortNumbersAsync(string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UI1_2_3.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UI1_2_3.ServiceReference1.IService1>, UI1_2_3.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CelsiusToFahrenheit(int celsius) {
            return base.Channel.CelsiusToFahrenheit(celsius);
        }
        
        public System.Threading.Tasks.Task<int> CelsiusToFahrenheitAsync(int celsius) {
            return base.Channel.CelsiusToFahrenheitAsync(celsius);
        }
        
        public int FahrenheitToCelsius(int fahrenheit) {
            return base.Channel.FahrenheitToCelsius(fahrenheit);
        }
        
        public System.Threading.Tasks.Task<int> FahrenheitToCelsiusAsync(int fahrenheit) {
            return base.Channel.FahrenheitToCelsiusAsync(fahrenheit);
        }
        
        public string SortNumbers(string s) {
            return base.Channel.SortNumbers(s);
        }
        
        public System.Threading.Tasks.Task<string> SortNumbersAsync(string s) {
            return base.Channel.SortNumbersAsync(s);
        }
    }
}
